### ISSUE TITLE
Updated virtualbox to 5.2.26

### ISSUE THREAD

**Issue by peterwwillis** [Ponce/slackbuilds#48]
Hello,

I did not see your repository earlier with virtualbox 5.2.8, so I went ahead and updated the old slackbuild of virtualbox to 5.2.26. I followed your method of creating a feature branch for the slackbuild, and here's the commit where I imported my changes: https://github.com/peterwwillis/slackbuilds/commit/c7d8f7dc3efb634cee0f65a84c9087683628619f

It adds one extra dependency (opus) which maybe could be disabled at build time, but it was needed for me to build virtualbox without changing anything else. It also includes a tiny patch for VBoxFUSE.

**Comment by Ponce** [comment]
Hi Peter, sorry for the late reply but I have just seen the issue...
I'm sorry, but virtualbox is maintained by Heinz Wiesinger: he updated just for this repository all of the components (not just virtualbox but also virtualbox-addons, virtualbox-extensions-pack, virtualbox-kernel and virtualbox-kernel-addons) to 5.2.8 some time ago because of problems in building it.
he explained that he avoided updating it for 14.2 because he didn't want to introduce qt5 as a dependency on that Slackware version.
you can see the various branch updates here (IMHO a clearer interface than github's) http://cgit.ponce.cc/slackbuilds/refs/heads
