### ISSUE TITLE
Some errors with the 'slackrepo_ponce.conf' file 

### ISSUE THREAD

**Issue by BusinessKid** [Ponce/slackbuilds#51]
I've had an absolutely weird time configuring this: I'm on a 250G ssd, and My setup is
sda1 -  common boot drive (small)       sda2 - common swap
sda3 - 30G Mint-19.0 (A spare system) Installed here as I wanted to move slackware /
sda4 - extended partition                      sda5 - 30G Slackware64 /home
sda6 - 25G Slackware64-Current /. This is tight enough on space.
sda7 - 135G on /mnt/virtual. This is scratch space, holding VM images, your slackrepo files. That explains some of the filenames.  You have everything nested under a plethora of directories which is a real PITA for me. I got hundreds of complaints about locations (can't create directory ' ') etc, and ended up sort of working. Here's the current file locations from /etc/slackrepo/slackrepo_ponce.conf
SBREPO="/mnt/virtual/slackrepo/%REPO%/slackbuilds-current"
SRCREPO=" /mnt/virtual/slackrepo/%REPO%/source"
PKGREPO="/mnt/virtual/slackrepo/ponce/Built_Recently"
HINTDIR="/etc/slackrepo/%REPO%/hintfiles"
DATABASE="/mnt/virtual/slackrepo/ponce/database_ponce_x86_64.sqlite3"
But I also needed these environment variables
REPO=ponce
SLACKVER=slackware-current
ARCH=x86_64
LOGDIR=/var/log
HINTDIR=/etc/slackrepo/%REPO%/hintfiles
DEFAULT_HINTDIR=/etc/slackrepo/%REPO%/default_hintfiles/slackware-current
and I'm left with unwanted files in the directory the root terminal is sitting in: 
1. openjdk,
2. jack2??# These substitutions are SBo dependencies that have been superseded by?# packages in Slackware-current. You can add more substitutions.?SUBSTITUTE= [That's the file name!]
3. A directory \ / (back slash, space, forward slash). This has a directory mnt/virtual/slackrepo/ponce/source/whatever. I built dice and pacman (failed, incidentally), so 'whatever' was games/{dice,pacman} with the source in each.

The docs presume a bit much. I hope for clarity & brevity in docs, and examples are good. This may be my fault, or yours

**Comment by Ponce** [comment]
I'm sorry but I don't use slackrepo and I really cannot help: try posting this on LQ, maybe someone else using slackrepo and this repository could step in.
BTW what I can tell you is:
1 - openjdk won't build, contact its maintainer.
2 - I haven't understood what the problem is.
3 - don't use spaces in directory's names.

**Comment by BusinessKid** [comment]
These appear to be from around line 70 in /etc/slackrepo/slackrepo_ponce.conf where you have extensive comments about Substitutions. It's reading some of your comments as configuration data - hence thje '#' openjdk, is there also. Very weird. I deleted the line and it puked on !lbwebp :-/. BTW, I won't post on a public forum what 'ponce' is slang for in Ireland & maybe the UK, but it's not good. Send me a PM on LQ.

**Comment by Ponce** [comment]
I'm not the author of those comments :-)
if I undesrtood what you're saying you are talking about an issue with a tool that uses this repository, not about something wrong with this repository, so this is not the proper place.
like I told you on LQ, and please don't get me wrong, I don't give a sh*t about what my nick means in ireland and UK, because it's related to [what it means here](https://translate.google.com/translate?sl=it&tl=en&u=https%3A%2F%2Fit.wikipedia.org%2Fwiki%2FPonce_(bevanda)), I hope the thing is cleared now...

**Comment by BusinessKid** [comment]
Your 'slackrepo' tool is parsing comments from it's own config file, and creating random and unwanted empty files  from words on the aforementioned comments. It is also  misplacing the downloaded source files. I don't see much pointy in taking that to LQ, If this is not the correct spot to raise this, please point me at the correct spot, and close this issue

**Comment by Ponce** [comment]
I think you got this wrong: slackrepo is not "my" tool.
You should be able to find contact infos for it where you downloaded: good luck!
