### ISSUE TITLE
Awesome 4.3 missing $PKG/usr/man 

### ISSUE THREAD

**Issue by Jigoku** [Ponce/slackbuilds#54]
```
-- Installing: /tmp/SBo/package-awesome/usr/doc/awesome-4.3/01-readme.md
-- Installing: /tmp/SBo/package-awesome/usr/doc/awesome-4.3/02-contributing.md
-- Installing: /tmp/SBo/package-awesome/usr/doc/awesome-4.3/LICENSE
-- Installing: /tmp/SBo/package-awesome/usr/share/xsessions/awesome.desktop
find: ‘/tmp/SBo/package-awesome/usr/man’: No such file or directory
```

This patch fixes the problem:
```
--- awesome.SlackBuild.orig	2019-04-13 21:11:14.990938250 +0100
+++ awesome.SlackBuild	2019-04-13 21:09:46.997199629 +0100
@@ -85,6 +85,7 @@
 find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
+mkdir -p $PKG/usr/man/
 find $PKG/usr/man -type f -exec gzip -9 {} \;
 for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
```

**Comment by Ponce** [comment]
I cannot replicate this on a clean and full installation of slackware current: I think something may be broken in your installation (missing some dependencies?) and man pages are not built.
BTW this is a repository current-specific, if you are not sure if your problem is current-specific (and may apply also to stable) a better place to report this would be in the [LQ forum](https://www.linuxquestions.org/questions/slackware-14/).

**Comment by Jigoku** [comment]
I am on latest -current with full base packages installed. Only seems to be this package that has this issue since 4.3.

**Comment by Ponce** [comment]
try posting a link to the full build log, maybe there are some hints there: use some service like http://pastebin.com for that.
