### ISSUE TITLE
libinput not found

### ISSUE THREAD

**Issue by CharlesDWard** [Ponce/slackbuilds#58]
libinput is listed as a qt5 dependency, but it doesn't exist on the current mirror (according to sbopkg)

**Comment by Ponce** [comment]
that's because libinput has been already included in Slackware current: I remove from the repository whatever is added to Slackware current to avoid overlaps.
in the meantime I don't fix the *.info files of the SlackBuild needing the above as dependencies until we go live on SBo with the repository for the newer version to avoid nightmares when rebasing the repository weekly (it's just unmanageable).
it's not really an error in sbopkg, it just says that it cannot find libinput in the repository but if you look in /var/log/packages/ it should be already there (it's assumed you are running a full installation).
other third party tools condider this an error but I cannot do much in this sense, sorry.

**Comment by CharlesDWard** [comment]
Sorry, I didn't know

Thanks for the clarification
