### ISSUE TITLE
Cannot sboupgrade python3-multidict to 4.7.5 (md5sum failure)

### ISSUE THREAD

**Issue by redblade7** [Ponce/slackbuilds#68]
Hi,

I can't upgrade python3-multidict to 4.7.5 when using sboupgrade. The file downloads successfully but the verification fails:

--2020-03-01 21:17:32--  ftp://slackware.uk/sbosrcarch/by-md5/9/a/9a1ed2cc0cd3e5dd2e71921104f2b760/multidict-4.7.5.tar.gz
           => ‘multidict-4.7.5.tar.gz’
Resolving slackware.uk (slackware.uk)... 2a02:2498:1:227::240:1, 91.109.244.240
Connecting to slackware.uk (slackware.uk)|2a02:2498:1:227::240:1|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /sbosrcarch/by-md5/9/a/9a1ed2cc0cd3e5dd2e71921104f2b760 ...
No such directory ‘sbosrcarch/by-md5/9/a/9a1ed2cc0cd3e5dd2e71921104f2b760’.

Unable to download/verify source file(s) for python3-multidict:
  md5sum failure for /usr/sbo/distfiles/multidict-4.7.5.tar.gz.

Do you want to proceed? [n]
Failures:
  python3-multidict: md5sum failure for /usr/sbo/distfiles/multidict-4.7.5.tar.gz.

**Comment by Ponce** [comment]
Hi @redblade7 : I think there's some misunderstanding here: this repository is a fork the main repository of SlackBuilds.org with modifications to build stuff on current.
what you are reporting in this issue is not related:
- to this repository
- to current
- to the main SBo repository
it seems that it's something that happens to you because you are using some third party tool to build your package and looks like is not working correctly: please refer to whoever offer support for that tool for help with this matter.

**Comment by redblade7** [comment]
Filed a bug at sbotools: https://github.com/pink-mist/sbotools/issues/80
