### ISSUE TITLE
gr-osmosdr still wont build

### ISSUE THREAD

**Issue by KenCoble** [Ponce/slackbuilds#76]
it complains about boost & endian

[ 70%] Building CXX object lib/CMakeFiles/gnuradio-osmosdr.dir/rtl_tcp/rtl_tcp_source_c.cc.o
/tmp/SBo/gr-osmosdr-20170612/lib/rtl/rtl_source_c.cc:35:10: fatal error: boost/detail/endian.hpp: No such file or directory
   35 | #include <boost/detail/endian.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [lib/CMakeFiles/gnuradio-osmosdr.dir/build.make:187: lib/CMakeFiles/gnuradio-osmosdr.dir/rtl/rtl_source_c.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:277: lib/CMakeFiles/gnuradio-osmosdr.dir/all] Error 2
make: *** [Makefile:161: all] Error 2

**Comment by KenCoble** [comment]
it seems to be tied to rtl-sdr & rtl-sdr tcp, i used the patch on a clean copy of the source, used ccmake  to disable all the sdr support except for soapy and it did build

**Comment by KenCoble** [comment]
and just a heads up, gqrx-sdr is going to need patched for this issue too, i think i should just stick with an older version of boost and it will resolve this whole mess

**Comment by Ponce** [comment]
you probably are missing an important point: in this repository I fix the building errors that someone might have building the various thousands of script available at SBo related to new additions/updates in a stock installation of slackware current, as things often break because of boost, icu4c, gcc, glibc, etc.
but I don't use a continuos integration tool like jenkins that rebuilds everything also with optional dependencies (like what is causing the additional errors in gr-osmosdr), I *try* fix things as they are reported to me: I just use this repository for my current installations and I add fixes trying to be helpful towards others, just don't expect that everything on SBo will be patched to work on Slackware's development platform.
in some cases patches are not even available, because upstream, like in these cases, doesn't even support building against boost >= 1.73.0, so I had to write them myself from scratch.
using an older version of boost won't solve anything because the rest of Slackware will break as it is build against the newer one.
the main point is this: if you feel more comfortable with Slackware stable keep using that.

**Comment by KenCoble** [comment]
ok, i will try to help you keep things going in current as i am able, will walk it back a step, and as it stands gr-osmosdr will not build unless i disable rtl-sdr support

**Comment by Ponce** [comment]
also uhd and who knows whatever else need extensive patching: I'm sorry but I don't have the necessary time to write patches for all of this stuff so I'll close this as WONTFIX.
