### ISSUE TITLE
After enabling vtown

### ISSUE THREAD

**Issue by livestradamus** [Ponce/slackbuilds#88]
Hi Ponce
I did a  slackpkg clean-system and have enabled testing/vtwon repository to test out plasma 5. 
I can't get quassel-qt5 to build. Any suggestions @Ponce ?

`In file included from /usr/include/qt5/QtCore/qobject.h:54,
                 from /usr/include/qt5/QtCore/qiodevice.h:45,
                 from /usr/include/qt5/QtNetwork/qabstractsocket.h:44,
                 from /usr/include/qt5/QtNetwork/qhostaddress.h:48,
                 from /usr/include/qt5/QtNetwork/QHostAddress:1,
                 from /tmp/SBo/quassel-0.13.1/src/common/dccconfig.h:23,
                 from /tmp/SBo/quassel-0.13.1/src/common/dccconfig.cpp:21:
/usr/include/qt5/QtCore/qmetatype.h: In instantiation of ‘static void QtMetaTypePrivate::QMetaTypeFunctionHelper<T, Accepted>::Load(QDataStream&, void*) [with T = DccConfig::PortSelectionMode; bool Accepted = true]’:
/usr/include/qt5/QtCore/qmetatype.h:1909:97:   required from ‘void qRegisterMetaTypeStreamOperators(const char*, T*) [with T = DccConfig::PortSelectionMode]’
/tmp/SBo/quassel-0.13.1/src/common/dccconfig.cpp:34:91:   required from here
/usr/include/qt5/QtCore/qmetatype.h:836:16: error: ambiguous overload for ‘operator>>’ (operand types are ‘QDataStream’ and ‘DccConfig::PortSelectionMode’)
  836 |         stream >> *static_cast<T*>(t);
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/qt5/QtCore/QDataStream:1,
                 from /tmp/SBo/quassel-0.13.1/src/common/syncableobject.h:24,
                 from /tmp/SBo/quassel-0.13.1/src/common/dccconfig.h:25,
                 from /tmp/SBo/quassel-0.13.1/src/common/dccconfig.cpp:21:
/usr/include/qt5/QtCore/qdatastream.h:419:1: note: candidate: ‘typename std::enable_if<std::is_enum<_Tp>::value, QDataStream&>::type& operator>>(QDataStream&, T&) [with T = DccConfig::PortSelectionMode; typename std::enable_if<std::is_enum<_Tp>::value, QDataStream&>::type = QDataStream&]’
  419 | operator>>(QDataStream &s, T &t)
      | ^~~~~~~~
In file included from /tmp/SBo/quassel-0.13.1/src/common/dccconfig.cpp:25:
/tmp/SBo/quassel-0.13.1/src/common/types.h:166:14: note: candidate: ‘QDataStream& operator>>(QDataStream&, T&) [with T = DccConfig::PortSelectionMode; <template-parameter-1-2> = void]’
  166 | QDataStream &operator>>(QDataStream &in, T &value) {
      |              ^~~~~~~~
make[2]: *** [src/common/CMakeFiles/mod_common.dir/build.make:238: src/common/CMakeFiles/mod_common.dir/dccconfig.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:528: src/common/CMakeFiles/mod_common.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

quassel-qt5:
Would you like to continue processing the rest of the
queue or would you like to abort?  If this failed
package is a dependency of another package in the queue
then it may not make sense to continue.

(Y)es to continue, (N)o to abort, (R)etry the build?:
`

**Comment by Ponce** [comment]
hi @livestradamus ,

if you have installed something from /testing please don't report any issues that you may encounter neither in this issue tracker nor in the LQ thread as things will eventually be evaluated/patched only when the stuff in /testing will go in the main distribution.
so you either are absolutely sure that your problem has nothing to do with the stuff in /testing (gcc, vtown, ecc.) or don't use the aforementioned channels (open a new dedicated topic on LQ, for example).
in this case, BTW, the problem is coincidentally not related at all with the stuff in /testing but it's because current ships a qt5 >= 5.14.x so quassel-qt5 needs a patch from upstream and I pushed it in a dedicated branch (will go in the main repository at the next merge)

https://github.com/Ponce/slackbuilds/tree/quassel-qt5
